### ISSUE TITLE
[Idea] Use fonctions from tnt mod

### ISSUE THREAD

**Issue by Salbei** [KasBrick/firedamp#1]
Maybe [tnt mod](https://github.com/minetest/minetest_game/tree/master/mods/tnt) functions can be used for more realistic effect.
Actually:
![screenshot_20150901_190602](https://cloud.githubusercontent.com/assets/6681662/9610819/2607a474-50dc-11e5-8ddc-ea0d4f4de951.png)

With the TNT mod:
![screenshot_20150901_190609](https://cloud.githubusercontent.com/assets/6681662/9610832/4414e54e-50dc-11e5-93d8-30cc4210b111.png)

**Comment by KasBrick** [comment]
Yes, I 'll watch that. Thanks ! ;)

**Comment by KasBrick** [comment]
Now Firedamp Mod is based on Tnt Mod. ;)
